adb shell pm disable-user com.google.android.youtube
adb shell pm disable-user com.google.android.googlequicksearchbox
adb shell pm disable-user com.google.android.apps.maps
adb shell pm disable-user com.google.android.gm
adb shell pm disable-user com.google.android.videos
adb shell pm disable-user com.android.chrome
adb shell pm disable-user com.google.android.music
adb shell pm disable-user com.google.android.apps.docs
adb shell pm disable-user com.sec.spp.push
adb shell pm disable-user com.sec.android.app.myfiles
adb shell pm disable-user com.sec.android.app.wallpaperchooser
adb shell pm disable-user com.sec.android.gallery3d
adb shell pm disable-user com.sec.android.mimage.photoretouching
adb shell pm disable-user com.sec.android.app.clockpackage
adb shell pm disable-user com.spotify.music